name: UltimateParticles
version: '${project.version}'
main: me.whiood.ultimateparticles.UltimateParticles
api-version: 1.19
authors: [ Whiood ]
description: Plugin for walking particles.

commands:
  trails:
    description: Command to turn on/off trails.
    usage: /<command>