name: UltimateTrails
version: 1.1
main: me.whiood.ultimatetrails.UltimateTrails
api-version: 1.19
authors: [ Whiood ]
description: Plugin for walking particles.

commands:
  trails:
    description: Command to turn on/off trails.
    usage: /<command>